version: '3.8'

services:
  vue-app:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
  # nginx:
  #   image: nginx:alpine
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Use custom Nginx configuration
  #   ports:
  #     - "80:80"  # Expose port 80 for public access
  #   depends_on:
  #     - vue-app